#!/bin/bash
# Supply a name for the section, the config dir, the domain, admin email and a test user like this.
# create_new_section newdomain Newdomain newdomain.com AdminEmail SomeUser
# That will create a number of variables for each word.
# $1 = newdomain
# $2 = NewDomain
# $3 = newdomain.com
# $4 = AdminEmail@newdomain.com
# $5 = SomeUser@newdomain.com
GAM=$HOME/gamadv-xtd3/gam
mkdir -p $HOME/.gam/$2
wait
#echo [$1]$'\n'domain = $3$'\n'config_dir = $2$'\n'customer_id = my_customer$'\n'>> .gam/gam.cfg
echo $'\n'[$1]$'\n'domain = $3$'\n'config_dir = $2$'\n'>> .gam/gam.cfg
wait
$GAM select $1 save
wait
$GAM create project admin $4
wait
$GAM oauth create admin $4
wait
#word="Customer ID:"
#cutFields=3
#$GAM info domain |
#while read -r line; do
#    if [[ "$line" == *$word* ]]; then
#        clean=$(echo ${line} | cut --delimiter=" " --fields=$cutFields)
#        echo customer_id = ${clean}$'\n'>> .gam/gam.cfg
#           break
#    fi
#done
echo -e "customer_id = $("${GAM}" info domain | awk '/Customer ID:/ { print $NF; exit }')\n" >> .gam/gam.cfg
wait
$GAM user $5 check serviceaccount
wait
$GAM select default
wait
echo 'Do what it says here above, before going forward.'
echo
echo 'AFTER you have followed the instructions above...'
echo
echo 'Copy and run this command to verify the DwD setting.'
echo gam select $1 user $5 check serviceaccount
echo
echo 'If all passes you are now ready to use GAMADV-XTD3.'
